# Generated by Django 5.0.1 on 2024-01-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='phtot_author',
            new_name='photo_author',
        ),
    ]
