# Generated by Django 5.0.1 on 2024-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_book_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, default='default-avatar-male.jpg', null=True, upload_to='photos'),
        ),
    ]
